### ISSUE TITLE
Issues with Wagyan Land 2 Translations

### ISSUE THREAD

**Issue by LodanZark** [libretro/libretro-fceumm#180] opened 2017-11-18 21:36 UTC
The Wagyan Land 2 translations appears to have glitch visuals in the latest fceumm meanwhile those works well on nestopia.

Latest fceumm:
![fceumm](https://i.imgur.com/G77UapE.png)

Nestopia:
![Nestopia](https://i.imgur.com/2le2uYM.png)

Hashs:

Name:	Wagyan Land 2 (J) [T+Eng1.0_Abstract Crouton Productions,Graphics1.0 Terminus].nes
SHA-1:	7D8D8FF3E3E3EC6B2CBE371C2BDCEDAA088B604E
MD5:	D4546379BA0FE7169734307787BDB04F
CRC32:	0041E20E

Name:	Wagyan Land 2 (J) [T-Eng1.0_Abstract Crouton Productions].nes
1839BD74AC64C7E56C2E07FAB88CF1C69AFF67
MD5:	67BD95B859C73C7F17A5B2F704B8FC98
CRC32:	E3564E48

**Comment by retro-wertz** [comment] 2017-11-19 00:03
this game is mapper 210. using the translated patch changes crc so
fceumm/fceux is not able to re-assign it anymore.

Change the header to use mapper 210 and the translation should be ok.

**Comment by retro-wertz** [comment] 2018-01-04 00:16
there to have been no update now... i say again, the issue is caused by the patch, which changed the crc of the file so fceumm is not able to apply the mapper required to run rom... manually changing rom header's mapper to 210 should solve this issue.

**Comment by ofry** [comment] 2018-01-11 10:55
Could you add crc's of these patches to your internal database?

**Comment by retro-wertz** [comment] 2018-01-11 11:37
i can, but since this is a patch, crc could change if its using a different patch like an update or so. best case is user should manually update header using header editing tools and set the game to mapper 210.

**Comment by ofry** [comment] 2018-01-11 11:49
Hm...

There are only 2 translations in RHDN database:

http://www.romhacking.net/?page=translations&genre=&platform=&status=&languageid=12&perpage=20&title=Wagyan+Land+2&author=&transsearch=Go

And both of that was NOT updated more than 10 years!

So, I think, you can add both of that to your database.

And in web exist many sites which provide pre-patched roms... Yes, I know, it's illegal, but many ppl downloading these roms and want to play with it.

**Comment by LodanZark** [comment] 2018-01-11 16:39
I used this tool to set the mapper to 210: https://www.romhacking.net/utilities/1352/
It works now ;)

**Comment by retro-wertz** [comment] 2018-01-14 01:39
@LodanZark ok thanks for confirmation. please close the issue. thanks.

**Closed** 2018-01-14 06:11 UTC
