### ISSUE TITLE
Mac OS X BurgerTime random resets

### ISSUE THREAD

**Issue by crlorent** [libretro/libretro-fceumm#182] opened 2017-12-12 18:10 UTC
Hello fceumm maintainers,
Mac OS X High Sierra 10.13.2
RetroArch 1.6.9
FCEUmm SVN 56b786d

I have been playing with the fceumm core for a couple days because I wanted RetroAcheivements support which Nestopia UE doesn't have. Unfortunately, on my Mac, the No-Intro BurgerTime rom I have will reset randomly before stage 2. This does not happen on Nestopia, or on Windows. I tried to run verbose logging of RetroArch, but I didn't see anything around the failure.

Is there a newer build for Mac OS X besides the nightly @ https://buildbot.libretro.com/nightly/apple/osx/x86_64/? Are their debug logs I can collect to help debugging?

Reset occured between Unpaused and Paused at the end of the log https://pastebin.com/6NF413WC

**Comment by retro-wertz** [comment] 2017-12-13 00:38
i cant seem to replicate the issue here although im not  using mac. recheck
you log especially when the game resets, log should show when the core is
actually calling a Reset. if not probably its something with Mac builds.

**Comment by crlorent** [comment] 2017-12-13 16:11
@retro-wertz Yeah I have no issue on Windows, it is only on my Mac System, unfortunately I don't have a second mac to test with. Another verbose log, nothing interesting that I can see. No Reset which would be seen if the user requested a reset.

https://pastebin.com/HyT8rsa5
Video of the issue: https://youtu.be/oXV0MWYydv4?t=48s - unexpected reset happens at 52s

It appears to be an issue with the Mac build. Are there debugging methods that can be used to help understand what is going on?

**Comment by retro-wertz** [comment] 2017-12-13 16:33
does any other nes games running any issues? not necessarily the same reset
issue but something like crashing etc. im not familiar with mac so not such
what debugging tools are available or how to use any.

**Comment by chipsnblip** [comment] 2017-12-16 03:10
according to your log, the ROM md5sum is "d2c42603a8ec74f51265c085ae26b9bb", but that could be an old/incorrect dump.  if possible, can you test with a ROM with md5sum of "924f89aad439db0ada794e23075d649f"?

**Comment by retro-wertz** [comment] 2017-12-16 23:15
the rom is officially known no-intro dump and the one in NescartDB. But Yeah, TS should try other dump of the rom, even the Japan version if it does the same thing.

**Comment by crlorent** [comment] 2017-12-17 18:55
@chipsnblip I am certainly willing to look for and test a different rom. and Will try withthe Japan rom as well to see if I get any differences, however, I am confused and concerned about being able to ensure I can find the "correct" rom and test the right thing. Are you concerned with matching the ROM MD5, the CHEEVOS hash, or the file MD5? Not sure if you have the rom you are thinking about and can also check the verbose log to see which items match/differ from mine.

The file MD5
924f89aad439db0ada794e23075d649f  BurgerTime (USA).nes

The verbose log checksums.
[libretro INFO]  ROM MD5:  0xd2c42603a8ec74f51265c085ae26b9bb
[INFO] [CHEEVOS]: getting game id for hash 9ff8f926f7284b2fa13fa9f5cc26cb23

So I guess I don't know if the file MD5 is what I should match, or if the ROM MD5 is what needs to match. I've had the No-Intro roms from a few different packs, and the GoodRoms versions and most of them are the same file md5...the latest file I tried (doesn't load on either Nestopia or FCEUmm...
d2c42603a8ec74f51265c085ae26b9bb  BurgerTime (USA).nes
I'v guessing this is a headerless rom, which matches the ROM MD5 info in the logs...but doesn't run in any emulator
`[libretro WARN] Missing header or invalid iNES format file!
[libretro WARN] FDS BIOS ROM image missing!
[libretro WARN] An error occurred while loading the file.`

@retro-wertz  - my limited testing of other games like Palemedes/II Contra, Dr. Mario, Super Mario Bros, Tetris, Krazy Kreatures, Punch-Out, shows no other issues.

**Comment by retro-wertz** [comment] 2017-12-18 07:38
it looks like both files are the same:

**[libretro INFO]  ROM CRC32:  0xdaf9d7e3
[libretro INFO]  ROM MD5:  0xd2c42603a8ec74f51265c085ae26b9bb**
This is the crc32/md5 of the rom without the 16-byte header.

**924f89aad439db0ada794e23075d649f BurgerTime (USA).nes**
Is the same file above with the header.

Both files are the same, expect one is without the iNES header and the other have. FCEUmm does not run without header.

@crlorent can you apply the Pizza Time hack from here? https://www.romhacking.net/hacks/2480/
I wonder if the rom itself is buggy since that rom hack says something about reset issue. Youjust need to place the patch (*.ips) together where Burger Time (USA) rom is and rename the ips exactly how the rom is named. example if the rom is **Burger Time (USA).zip** or **Burger Time (USA).nes**, the patch should be named **Burger Time (USA).ips**

**Comment by crlorent** [comment] 2017-12-19 19:11
Unfortunately it fails in the same way with the Pizza Time patch (FCUEmm fails, QuickNES Fails, Nestopia UE works fine). I wish someone with Mac development knowledge was on this project page who could ask me to grab specific data to help. Oh Well, Luckily this is a work system and I don't often need an NES break on it, and If I really want to play BurgerTime without the ability to get Achievements I can use Nestopia.

**Comment by retro-wertz** [comment] 2017-12-24 12:15
@crlorent  as an alternative, you can also use QuickNES if its available for the device you have. its compatible with retroachievements too.

**Comment by meepingsnesroms** [comment] 2017-12-25 04:14
Its not random.
I am working on this issue and you can almost reproduce this 100% of the time by walking all the way to the edge of the screen and turning around.

This should be fixed soon, this carts mapper has a reset option built in, so something is likely going wrong with that.

**Comment by meepingsnesroms** [comment] 2017-12-25 18:23
The issue seems fixed, BurgerTime has a mapper of 233 but the nointro rom says its mapper 0, apply this ips patch and see if it still resets.
[BurgerTimeCorrectMapper.ips.zip](https://github.com/libretro/libretro-fceumm/files/1586069/BurgerTimeCorrectMapper.ips.zip)

If you are a developer you can also open the rom in this: [Ines Header Editor](https://www.romhacking.net/utilities/1352/)

FCEUmm is working fine, nointro is broke.

**Closed by meepingsnesroms** 2017-12-25 18:23 UTC

**Comment by retro-wertz** [comment] 2017-12-25 20:56
Burger Time is a Namcot game. Mapper 233 is assigned to a pirate mapper for
42-in-1. Its strage that Nointo could have gotten the mapper assignment for
this rom wrong, let alone goodnes, nescartdb and all other latest nes
emulators that have its own database.

Also, the rom does not write to any registers in mapper 233, thats why its
a mapper 0.

**Comment by meepingsnesroms** [comment] 2017-12-26 06:06
[https://wiki.nesdev.com/w/index.php/INES_Mapper_233](https://wiki.nesdev.com/w/index.php/INES_Mapper_233)

I have heard nointro doesnt have headers so whoever added the header could have got it wrong.

**Comment by retro-wertz** [comment] 2017-12-26 06:38
no intro normally detects orly prg and chr portion of the rom, not the
header. you can check header info from goodnes though, or nescartdb or
other emulators having their own database.

if that is not enough, burger time has 16kb prg and 8kb chr and does not
write to any registers which is how mapper 0 is. but yeah you probably know
something these people who assigned the mapper #'s did not....

**Comment by crlorent** [comment] 2018-01-02 21:26
Well, the new mapper (233) continues to fail with FCEUmm on my Mac. I'll take a look at the prg and chr values when I am next on my pc and can use the ines editor.

Fails at load on QuickNES. Fails to display on Nestopia, and still random resets on FCEUmm.

**Comment by retro-wertz** [comment] 2018-01-02 21:38
because that mapper 233 is basically a multicart mapper 0 cart, so it has registers but only used for switching between the games on that cart, not game-related regs.

you should reopen this issue as clearly it has not been resolved or at least a good workaround.

anyways the retroarch version and fceumm version you have is a bit old, is it possible you can update those and re-test?

**Comment by crlorent** [comment] 2018-01-08 15:36
I Wish I could re-open the request, however, it looks like @meepingsnesroms closed it can I don't have the rights  to open if a contributor closed it. Updated retroarch, fceumm, same situation with the correct mapper 0 file. Oh well, since no one else is reporting and I only play it sometimes on my Mac, maybe I'll install a Windows VM, or just play with Nestopia and ignore Achievements.

**Comment by retro-wertz** [comment] 2018-01-11 09:56
ic. is so, you should open a new issue then. also if possible, is there any other nes emulator available for your device? it would be nice if you are able to test other nes emu there if it behaves the same with this game. something thats fce/fceu/fceumm based should be nice.

i once have cloned a repo name FceuMAC (or was it MacFceu?) maybe they still exist?
