### ISSUE TITLE
Unable to load old save states

### ISSUE THREAD

**Issue by vretro** [libretro/libretro-fceumm#215] opened 2018-05-01 20:01 UTC
Known working save states created in 2016 are not loading in the current version of lr-fceumm at time of posting this issue.

**Comment by retro-wertz** [comment] 2018-05-01 21:16
this is not a bug..

**Comment by vretro** [comment] 2018-05-02 20:03
Thank you @retro-wertz

Is it an issue if the expected behaviour is that loading a saved state from disk would continue to resume the play session after a software update as before?

Are there any work arounds (converting to another format?)

**Comment by retro-wertz** [comment] 2018-05-03 04:58
yes, the the thing about save states, they are not meant to be primary data storage since that state handling can change as necessary. I am one on those who doesn't like states to change, especially for NES since most of the games do not have native saves RAM and would take hours redoing stuff, but i do not have last say about those things...

if you are able to upload you state files and upload in the forums, i may be able to convert some of them when I am not bz.

**Comment by vretro** [comment] 2018-05-13 20:03
Thank you @retro-wertz that is very kind.

I have zipped up a folder with the latest save state at the root directory:
https://we.tl/yZL62uvlHo

Would your conversion be something which could be automated as a script?

**Comment by retro-wertz** [comment] 2018-05-14 02:36
Thanks. can i assume that this state is for Super Mario Bros. 3 (USA) version? (not the Rev.1 one)

if so, take a look at this state if this works for you. this was from the one named **Super Mario Bros. 3.state34**

note i am using state slot #0 so rename this as necessary or backup you old states before using this.


[Super Mario Bros. 3 (USA).state.zip](https://github.com/libretro/libretro-fceumm/files/1999223/Super.Mario.Bros.3.USA.state.zip)

**Comment by meepingsnesroms** [comment] 2018-06-21 15:20
The state format changed, if you are still having format conversion talks feel free to keep posting here but this is not a emulator bug so I am closing it.

**Closed by meepingsnesroms** 2018-06-21 15:20 UTC

**Comment by KaibutsuX** [comment] 2018-12-03 23:47
@retro-wertz is there any documentation on how to manually or script a conversion? I have lots of state files for NES that I would love to use in newer versions but for now I am stuck on an old version because of this commit which breaks all of my state files:

0343e3dbd8a22f64698e824e30b08e0887d77b6b

I realize it's not a bug, but I think there could be an option or script that could normalize any existing state files. If you have any documentation, I'm up for writing a conversion script.
