### ISSUE TITLE
Unable to open Super Game 143-in-1 (The Best Games Of NES) (Mindkids) (Unl)

### ISSUE THREAD

**Issue by Gita1997** [libretro/libretro-fceumm#294] opened 2019-08-06 14:38 UTC
Hello please correct the error? Unable to open Super Game 143-in-1 (The Best Games Of NES) (Mindkids) (Unl) freezes the system, the older version it was running fine.
PS3 Version Fceumm 0b0c76a,
the previous version of fceumm opened the game, Thank you very much
same error as 90 in 1 Hwang Shinwei
Thank you for your work

**Comment by Gita1997** [comment] 2019-08-06 15:41
Really, please tested PS3 Version fceumm

**Comment by hizzlekizzle** [comment] 2019-10-28 22:54
Closing as duplicate of #290

**Closed by hizzlekizzle** 2019-10-28 22:54 UTC
