### ISSUE TITLE
Update Fceumm

### ISSUE THREAD

**Issue by Leonyd10** [libretro/libretro-fceumm#301] opened 2019-10-28 12:33 UTC
hello, when will the new update?
Hundreds of mappings are missing.
other emulators add mappers every now and then ( Nintendulator, Nestopia Plus)
Perhaps we will not be left behind with such little mapping support
Thank you for understanding

**Comment by Leonyd10** [comment] 2019-10-28 12:36
I forgot to point out yet
fceumm is missing the Soft and Hard Reset functions to switch multicart menu

**Comment by hizzlekizzle** [comment] 2019-10-28 22:54
Closing as duplicate of #290

**Closed by hizzlekizzle** 2019-10-28 22:54 UTC
Labels: duplicate
